# Generated by Django 5.1.2 on 2024-10-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_system_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_task',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
